//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EasyDRF.rc
//
#define IDSAVE                          2
#define ID_CHOOSEFILE                   2
#define IDAPP                           2
#define ID_SETDEFMIXER                  2
#define ID_DELALLFILES                  3
#define ID_SET_A_MAXSPEED               3
#define ID_SET_B_DEFAULT                4
#define ID_DELALLFILES2                 4
#define ID_CANCELPICTX                  5
#define IDC_ADDALLFILES                 6
#define IDS_WAVE_PANE                   101
#define DLG_MAIN                        106
#define DLG_ABOUT                       107
#define DLG_CALLSIGN                    108
#define ICO_FFT                         110
#define ID_SETTINGS_COMPORT             114
#define ID_COMPORT_COM1                 115
#define ID_COMPORT_COM2                 116
#define ID_COMPORT_COM3                 117
#define ID_COMPORT_COM4                 118
#define ID_SETTINGS_RXSOUNDCARD         119
#define ID_SETTINGS_TXSOUNDCARD         120
#define IDR_MENU1                       121
#define ID_SETTINGS_PTTPORT             124
#define ID_PTTPORT_COM1                 125
#define ID_PTTPORT_COM2                 126
#define ID_PTTPORT_COM3                 127
#define ID_PTTPORT_COM4                 128
#define ID_PTTPORT_NONE                 129
#define ID_RXSOUNDCARD_DUMMY            130
#define ID_DUMMY_DUMMY                  131
#define ID_TXSOUNDCARD_DUMMY            132
#define ID_SOUNDCARD_                   133
#define ID_ABOUT                        134
#define ID_ABOUT_TEST                   135
#define ID_SETTINGS_CALLSIGN            137
#define ID_SETTINGS_DISPLAY             138
#define ID_DISPLAY_SPECTRUM             139
#define ID_DISPLAY_PSD                  140
#define ID_SETTINGS_MODE                141
#define ID_SETTINGS_CODEC               142
#define ID_CODEC_SPEEX                  143
#define ID_CODEC_LPC10                  144
#define ID_MODE_ROBMODEA                145
#define ID_MODE_ROBMODEB                146
#define ID_MODE_ROBMODEE                147
#define ID_SETTINGS_INTERLEAVE          148
#define ID_INTERLEAVE_SHORT400MS        149
#define ID_INTERLEAVE_LONG2S            150
#define ID_SETTINGS_MSCCODING           151
#define ID_MSCCODING_16QAM              152
#define ID_MSCCODING_64QAM              153
#define ID_DISPLAY_LEVEL                154
#define IDI_ICON1                       155
#define DLG_DRMSETTINGS                 156
#define DLG_TEXTMESSAGE                 157
#define DLG_RXTEXTMESSAGE               158
#define DLG_PICTURE_TX                  159
#define DLG_HELP                        160
#define DLG_RXSETTINGS                  161
#define DLG_MIXERSETTING                162
#define DLG_SENDBSR                     163
#define DLG_ANSWERBSR                   164
#define ID_TXLEVEL                      165
#define IDM_O_RX_I_DRIVERS0             200
#define IDM_O_TX_O_DRIVERS0             250
#define IDM_O_VO_I_DRIVERS0             300
#define IDM_O_VO_O_DRIVERS0             350
#define IDM_O_END_DRIVERS0              400
#define IDS_FREQ_PANE                   1002
#define IDB_START                       1003
#define IDB_STARTPIC                    1004
#define IDC_MODE_A                      1005
#define IDC_MODE_B                      1006
#define IDC_CODEC                       1008
#define IDC_EDIT                        1013
#define IDC_EDIT2                       1014
#define IDC_TIME_SCALE                  1015
#define IDC_EDIT3                       1016
#define IDC_FREQ_SCALE                  1017
#define IDC_EDIT4                       1018
#define IDC_DCFREQ                      1019
#define IDC_EDIT5                       1020
#define IDC_PROGRESS1                   1021
#define IDC_PROGRESS2                   1026
#define IDC_EDIT1                       1027
#define IDC_DCOFFS                      1031
#define IDC_TUNINGTONE                  1032
#define IDC_TEXTMESSAGE                 1033
#define IDC_USETEXTMESSAGE              1034
#define IDC_RXTEXTMESSAGE               1035
#define IDC_RESETACQ                    1036
#define IDC_GETPICANY                   1037
#define IDC_PICFILE_TX                  1038
#define IDC_SENDTWICE                   1039
#define IDC_SENDONCE                    1040
#define IDC_FREQACC                     1041
#define IDC_SENDTHREE                   1042
#define IDC_SEARCHWINLOWER              1043
#define IDC_IDTONE                      1043
#define IDC_SENDTHREE2                  1043
#define IDC_SOUNDCARDNAME               1044
#define IDC_SENDTHREE3                  1044
#define IDC_LEADINLONG                  1045
#define IDC_SENDBSR                     1045
#define IDC_SEARCHWINUPPER              1046
#define IDC_GTONE                       1046
#define IDC_SENDTHREE4                  1046
#define IDC_LISTRX                      1047
#define IDC_BTONE                       1047
#define IDC_SENDTHREE5                  1047
#define IDC_LISTTX                      1048
#define IDC_SENDBSR_FNAME               1048
#define IDC_SENDBSR_NOSEG               1049
#define ID_MSCCODING_4QAM               1050
#define ID_SET_B_ROBUST                 1051
#define IDC_BSRINST                     1053
#define IDC_SENDNOBSR                   1054
#define IDC_SENDNAMEBSR                 1055
#define IDC_SETTINGS_FASTRESET          1057
#define IDC_SENDBSR_FROMCALL            1058
#define IDC_SENDCALLBSR                 1059
#define ID_ABSRINST                     1060
#define IDOK3                           1061
#define IDC_EDIT6                       1062
#define IDC_EDIT7                       1063
#define IDC_RXFILES                     1064
#define IDC_RS1                         1065
#define IDC_RS2                         1066
#define IDC_RS3                         1067
#define IDC_RS4                         1068
#define ID_SETTINGS_MSCPROTECTION_NORMAL 40001
#define ID_SETTINGS_MSCPROTECTION_LOW   40002
#define ID_SETTINGS_DRMSETTINGS         40003
#define ID_SETTINGS_BW_25               40003
#define ID_SETTINGS_TEXTMESSAGE         40004
#define ID_SETTINGS_BW_23               40004
#define ID_SETTINGS_TEXTMESSAGE_OPENRXTEXTMESSAGE 40007
#define ID_SETTINGS_DISPLAY_WATERFALL   40008
#define ID_SETTINGS_DISPLAY_TRANSFERFUNCTION 40009
#define ID_SETTINGS_DISPLAY_IMPULSERESPONSE 40010
#define ID_SETTINGS_DISPLAY_FACPHASE    40011
#define ID_SETTINGS_DISPLAY_MSCPHASE    40012
#define ID_SETTINGS_FILETRANSFER_SAVERECEIVEDFILES 40014
#define ID_SETTINGS_FILETRANSFER_SENDFILE 40015
#define ID_SETTINGS_AUDIOFILTER_RXFILTER 40017
#define ID_ABOUT_HELP                   40019
#define ID_SETTINGS_DRMSETTINGSRX       40020
#define ID_SOUNDCARD_OPENMIXER_RXINPUT  40022
#define ID_SOUNDCARD_OPENMIXER_TXOUTPUT 40023
#define ID_SOUNDCARD_OPENMIXER_VOICEINPUT 40024
#define ID_SOUNDCARD_OPENMIXER_VOICEOUTPUT 40025
#define ID_SOUNDCARD_AUTOMIXERSWITCH    40031
#define ID_PTTPORT_COM5                 40032
#define ID_PTTPORT_COM6                 40033
#define ID_PTTPORT_COM7                 40034
#define ID_PTTPORT_COM8                 40035
#define ID_SETTINGS_PTTPORT_RTSHIGHONFAC 40036
#define ID_SETTINGS_DISPLAY_TEST        40037
#define ID_SETTINGS_FILETRANSFER_SHOWRECEIVEDFILES 40040
#define ID_SETTINGS_FILETRANSFER_SHOWONLYONE 40041
#define ID_SETTINGS_PTTPORT_DTRHIGHONFAC 40042
#define ID_SETTINGS_LOADLASTRXFILE      40043
#define ID_SETTINGS_DISPLAY_OSCILLOSCOPE 40045
#define ID_SETTINGS_VOICECOMPRESSOR     40046
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         40047
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
